language: python
python:
  - 3.5.0
  - 3.5.2
  - 3.6
sudo: false

before_install:
  - pip install -Ur test-requirements.txt
  - pip install codecov

install:
  - python setup.py sdist --formats=zip
  - pip install dist/*.zip

script:
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os, async_generator; print(os.path.dirname(async_generator.__file__))")
  - py.test --pyargs async_generator --cov="$INSTALLDIR" --cov-config=../.coveragerc


after_success:
  - codecov
