language: python
python:
  - 3.5.0
  - 3.5.2
  - 3.6
sudo: false

before_install:
  - pip install -Ur test-requirements.txt
  - pip install codecov

install:
  - pip install .

script:
  - mkdir empty
  - cd empty
  - py.test --pyargs async_generator --cov=async_generator --cov-config=.coveragerc


after_success:
  - codecov
