language: python
python:
  - 3.5
sudo: false

before_install:
  - pip install -r test-requirements.txt
  - pip install codecov

script:
#  - py.test --cov=async_generator --cov-config=.coveragerc
  - py.test


after_success:
  - codecov
