[tool.towncrier]
package = "async_generator"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/python-trio/trio/issues/{issue}>`__"
